### PR TITLE
CUDA - shared basis needs minimum of 1 elem per block

### LINKED ISSUE #462: CUDA + PETSc BPs
When running the test suite, I have the following errors on PETSc BPsRaw with the following backends:

`/gpu/cuda/ref`
```
/home/jeth8984/libCEED/backends/cuda/ceed-cuda.c:81 in CeedCompileCuda(): CUDA_ERROR_INVALID_PTX
```

`/gpu/cuda/shared`
```
/home/jeth8984/libCEED/backends/cuda/ceed-cuda.c:110 in CeedRunKernelDimCuda(): CUDA_ERROR_INVALID_VALUE
```

Test parameters
```
# TESTARGS: -ceed {ceed_resource} -test -problem bp2 -degree 5 -qextra 5
```

I intentionally set the test parameters to use almost twice as many qpts as nodes. Dropping to `-qextra 2` fixes the failures. Should we modify the test parameters to something more realistic, try to hunt the issues, or both?

There is also a floating point exception with `petsc-area` and `petsc-bpssphere` for `cuda/shared`.

### PR DESCRIPTION
**Pull request by jeremylt**
Closes #462

We were getting a small divide by zero that I've corrected. Now `petsc-area` and `petsc-bpssphere` pass with all backends.

### CODE REVIEW

**Comment by jeremylt** [comment]
```
[jeremy@sinensis libCEED]$ OCCA_DIR= make -j8 prove search=petsc
make: 'lib' with optional backends: /cpu/self/memcheck/serial /cpu/self/memcheck/blocked /cpu/self/avx/serial /cpu/self/avx/blocked /cpu/self/xsmm/serial /cpu/self/xsmm/blocked /gpu/cuda/ref /gpu/cuda/reg /gpu/cuda/shared /gpu/cuda/gen /gpu/magma /cpu/self/tmpl /cpu/self/tmpl/sub
Testing backends: /cpu/self/ref/serial /cpu/self/ref/blocked /cpu/self/opt/serial /cpu/self/opt/blocked /cpu/self/memcheck/serial /cpu/self/memcheck/blocked /cpu/self/avx/serial /cpu/self/avx/blocked /cpu/self/xsmm/serial /cpu/self/xsmm/blocked /gpu/cuda/ref /gpu/cuda/reg /gpu/cuda/shared /gpu/cuda/gen /gpu/magma /cpu/self/tmpl /cpu/self/tmpl/sub
prove -j 16 --exec 'tests/tap.sh' petsc-area petsc-bps petsc-bpsraw petsc-bpssphere petsc-multigrid
petsc-area ....... ok                                                   
petsc-bpssphere .. ok                                                   
petsc-bps ........ ok                                                   
petsc-bpsraw ..... ok                                                   
petsc-multigrid .. ok     
All tests successful.
Files=5, Tests=225, 26 wallclock secs ( 0.05 usr  0.00 sys + 58.29 cusr 15.29 csys = 73.63 CPU)
Result: PASS
```

File: backends/cuda-shared/ceed-cuda-shared-basis.c [hunk 1]
```diff
@@ -781,7 +781,8 @@ int CeedBasisApplyTensor_Cuda_shared(CeedBasis basis, const CeedInt nelem,
                                         interpargs); CeedChk(ierr);
     } else if (dim == 2) {
       const CeedInt optElems[7] = {0,32,8,6,4,2,8};
-      CeedInt elemsPerBlock = Q1d < 7 ? optElems[Q1d]/ncomp : 1;
+      // elemsPerBlock must be at least 1
+      CeedInt elemsPerBlock = (Q1d < 7 ? optElems[Q1d]/ncomp : 1) || 1;
```
Comment (YohannDudouit) [inline backends/cuda-shared/ceed-cuda-shared-basis.c:785]: I don't understand how this can work, `||` returns a `bool`, so all this is doing is returning `1`, or am I missing something?

Comment (jeremylt) [reply backends/cuda-shared/ceed-cuda-shared-basis.c:785]: I'm using short circuiting. I could also write this as a ternary, but it would be longer.

Comment (jeremylt) [reply backends/cuda-shared/ceed-cuda-shared-basis.c]: That's what I get for trying to be clever. `||` indeed returns a bool which is converted to `1`. Updated.
