### PR TITLE
Fix Style Indentation Errors

### LINKED ISSUE #396: Make Style
`make style` introduces several errors that have to be manually reverted.

### PR DESCRIPTION
**Pull request by jeremylt**
Astyle struggles with some of our indentation. This PR make some small changes and adds `INDENT-OFF` where needed so that we can run `make style` without needing manual fixes.

Fixes #396

### CODE REVIEW

File: backends/cuda-reg/ceed-cuda-reg-basis.c [hunk 1]
```diff
@@ -21,6 +21,7 @@
 
 //*********************
 // reg kernels
+// *INDENT-OFF*
```
Comment (jeremylt) [inline backends/cuda-reg/ceed-cuda-reg-basis.c]: Asyle has no clue how to handle these quoted kernels.

File: examples/mfem/bp1.hpp [hunk 2]
```diff
@@ -115,8 +115,8 @@ class CeedMassOperator : public mfem::Operator {
     const int ir_order = 2*(order + 2) - 1; // <-----
     const mfem::IntegrationRule &ir =
       mfem::IntRules.Get(mfem::Geometry::SEGMENT, ir_order);
-    CeedInt nqpts, nelem = mesh->GetNE(), dim = mesh->SpaceDimension(),
-            ncompx = dim;
+    CeedInt nelem = mesh->GetNE(), dim = mesh->SpaceDimension(),
```
Comment (jeremylt) [inline examples/mfem/bp1.hpp]: When there is a mix of declarations with and without initializations, astyle indents correctly when the initializations come first.

File: examples/navier-stokes/densitycurrent.h [hunk 3]
```diff
@@ -78,15 +78,21 @@
 CEED_QFUNCTION(ICsDC)(void *ctx, CeedInt Q,
                       const CeedScalar *const *in, CeedScalar *const *out) {
 
+// *INDENT-OFF*
```
Comment (jeremylt) [inline examples/navier-stokes/densitycurrent.h]: Astyle tries to reverse indent this. The behavior of preproc linting inside of functions is apparently undefined and won't be fixed.

File: gallery/poisson3d/ceed-poisson3dapply.h [hunk 4]
```diff
@@ -42,6 +42,7 @@ CEED_QFUNCTION(Poisson3DApply)(void *ctx, const CeedInt Q,
     // 0 5 4
     // 5 1 3
     // 4 3 2
+    // *INDENT-OFF*
     const CeedScalar dXdxdXdxT[3][3] = {{qd[i+0*Q],
```
Comment (jeremylt) [inline gallery/poisson3d/ceed-poisson3dapply.h]: Astyle really hates writing this style and wants to explode the array so that braces each have their own line.

Comment (jedbrown) [reply gallery/poisson3d/ceed-poisson3dapply.h]: We could consider packing such arrays via a loop or even a macro/function call (though we'd have to make it available on the CUDA/JIT side as well).

Comment (jeremylt) [reply gallery/poisson3d/ceed-poisson3dapply.h]: Right, I think that would be preferable so we can minimize the use of `INDENT-OFF`

Comment (jeremylt) [reply gallery/poisson3d/ceed-poisson3dapply.h]: Updated

File: examples/ceed/ex2.h [hunk 5]
```diff
@@ -103,20 +103,21 @@ CEED_QFUNCTION(f_apply_diff)(void *ctx, const CeedInt Q,
...
-      const CeedScalar dXdxdXdxT[2][2] = {{qdata[i+0*Q],
-                                           qdata[i+2*Q]},
-                                          {qdata[i+2*Q],
-                                           qdata[i+1*Q]}};
-      // *INDENT-ON*
+      const CeedInt idx[] = {0, 2, 2, 1};
+      CeedScalar dXdxdXdxT[2][2];
+      for (CeedInt m=0; m<2; m++)
+        for (CeedInt n=0; n<2; n++)
+          dXdxdXdxT[m][n] = qdata[i+idx[n+2*m]*Q];
```
Comment (valeriabarra) [inline examples/ceed/ex2.h]: Are we sure this is the preferred way we want this? It seems to me that it is harder to read and therefore to spot bugs, than fixing indentation style by hand, if/when needed

File: examples/ceed/ex2.h [hunk 6]
```diff
@@ -111,11 +111,11 @@ CEED_QFUNCTION(f_apply_diff)(void *ctx, const CeedInt Q,
       // Stored in Voigt convention
       // 0 2
       // 2 1
-      const CeedInt idx[] = {0, 2, 2, 1};
+      const CeedInt idx[2][2] = {{0, 2}, {2, 1}};
       CeedScalar dXdxdXdxT[2][2];
       for (CeedInt m=0; m<2; m++)
         for (CeedInt n=0; n<2; n++)
-          dXdxdXdxT[m][n] = qdata[i+idx[n+2*m]*Q];
+          dXdxdXdxT[m][n] = qdata[i+idx[m][n]*Q];
```
Comment (valeriabarra) [inline examples/ceed/ex2.h]: With the 2D array indices it reads a bit better, but it still looks to me more time consuming to read/debug/write this than the previous version

File: examples/ceed/ex2.h (hunk 5 above)
Comment (jeremylt) [reply examples/ceed/ex2.h]: I'm happy with dropping 2f40c9d502a896ccbf8765d62c5bdd42b5843f70 and cfd0a8060ed6616b70ae77e2243fb3d74a7dd253 if everyone prefers, but without doing something `make style` is useless - fixing errors in 20+ files every time is not practical.

I think this comes back to the same discussion in https://github.com/CEED/libCEED/pull/323

**Comment by jeremylt** [comment]
@jedbrown, any strong preference between

```
    const CeedInt idx[2][2] = {{0, 2}, {2, 1}};
    CeedScalar dXdxdXdxT[2][2];
    for (CeedInt m=0; m<2; m++)
      for (CeedInt n=0; n<2; n++)
```
and 
```
    const CeedScalar dXdxdXdxT[2][2] = {{qd[i+0*Q],
                                         qd[i+2*Q]},
                                        {qd[i+2*Q],
                                         qd[i+1*Q]}
                                       };
```

I think that's the last thing to settle on this PR.

**Comment by jedbrown** [comment]
I have a mild preference for the latter unless we're encapsulating that pattern in a macro so that it's a one-liner in QFunctions. We may want that eventually, but I don't see a pressing need to do it now.

**Comment by jeremylt** [comment]
Updated to drop the loops. This should be good to go now and we can use `make style` again.

**Comment by valeriabarra** [comment]
Just curious, will we have to filter-out the python interface once we have that up, to preserve the intended indentations there?

LGTM though. Thanks.

**Comment by jeremylt** [comment]
I'm not sure how this will handle python. I'm curious to see.
