### PR TITLE
Test for assembly w/non-square D

### LINKED ISSUE #987: Operator Assembly Fails with mismatched input & output
Given an operator, the `CeedOperatorLinearAssemble[Diagonal]` operation works only if the each input for the operator's QFunction has a matching output with the same `CeedEvalMode`. This was first discovered in the fluids example here, but is mostly easily/simply demonstrated via a Ratel test. Specifically, [t103](https://gitlab.com/micromorph/ratel/-/blob/main/tests/t103-static-elasticity.c) while applying the following patch:
<details>
<summary>Patch</summary>

```patch
diff --git i/src/ratel-fem.c w/src/ratel-fem.c
index 61efffc..efe644d 100644
--- i/src/ratel-fem.c
+++ w/src/ratel-fem.c
@@ -541,6 +541,10 @@ PetscErrorCode RatelSetupResidualJacobian_FEM(Ratel ratel, RatelMaterialData mat
     RatelDebug(ratel, "---- Setting up Jacobian evaluator");
     CeedQFunction qf_jacobian;
     CeedOperator  op_jacobian;
+    PetscBool testin      = PETSC_FALSE,
+              testingrad  = PETSC_FALSE,
+              testout     = PETSC_FALSE,
+              testoutgrad = PETSC_FALSE;
 
     // -- QFunction
     RatelCeedCall(ratel, CeedQFunctionCreateInterior(ceed, 1, material_data->jacobian, material_data->jacobian_loc, &qf_jacobian));
@@ -554,7 +558,11 @@ PetscErrorCode RatelSetupResidualJacobian_FEM(Ratel ratel, RatelMaterialData mat
       RatelCeedCall(ratel, CeedQFunctionAddInput(qf_jacobian, material_data->field_names[i], material_data->field_sizes[i], CEED_EVAL_NONE));
       // *INDENT-ON*
     }
+    if(testin) RatelCeedCall(ratel, CeedQFunctionAddInput(qf_jacobian, "testin", num_comp_u, CEED_EVAL_INTERP));
+    if(testingrad) RatelCeedCall(ratel, CeedQFunctionAddInput(qf_jacobian, "testingrad", num_comp_u*dim, CEED_EVAL_GRAD));
     RatelCeedCall(ratel, CeedQFunctionAddOutput(qf_jacobian, "delta dv", num_comp_u * dim, CEED_EVAL_GRAD));
+    if(testout) RatelCeedCall(ratel, CeedQFunctionAddOutput(qf_jacobian, "testout", num_comp_u, CEED_EVAL_INTERP));
+    if(testoutgrad) RatelCeedCall(ratel, CeedQFunctionAddOutput(qf_jacobian, "testoutgrad", num_comp_u*dim, CEED_EVAL_GRAD));
     if (ratel->method == RATEL_METHOD_DYNAMIC_ELASTICITY) {
       RatelCeedCall(ratel, CeedQFunctionAddOutput(qf_jacobian, "delta v", num_comp_u, CEED_EVAL_INTERP));
     }
@@ -572,6 +580,10 @@ PetscErrorCode RatelSetupResidualJacobian_FEM(Ratel ratel, RatelMaterialData mat
                                                 stored_fields[i]));
       // *INDENT-ON*
     }
+    if(testin) RatelCeedCall(ratel, CeedOperatorSetField(op_jacobian, "testin", elem_restr_u, basis_u, CEED_VECTOR_ACTIVE));
+    if(testout) RatelCeedCall(ratel, CeedOperatorSetField(op_jacobian, "testout", elem_restr_u, basis_u, CEED_VECTOR_ACTIVE));
+    if(testingrad) RatelCeedCall(ratel, CeedOperatorSetField(op_jacobian, "testingrad", elem_restr_u, basis_u, CEED_VECTOR_ACTIVE));
+    if(testoutgrad) RatelCeedCall(ratel, CeedOperatorSetField(op_jacobian, "testoutgrad", elem_restr_u, basis_u, CEED_VECTOR_ACTIVE));
     if (ratel->method == RATEL_METHOD_DYNAMIC_ELASTICITY) {
       RatelCeedCall(ratel, CeedOperatorSetField(op_jacobian, "delta u", elem_restr_u, basis_u, CEED_VECTOR_ACTIVE));
       RatelCeedCall(ratel, CeedOperatorSetField(op_jacobian, "delta v", elem_restr_u, basis_u, CEED_VECTOR_ACTIVE));

```
</details>

The above will pass t103, but any combination of the booleans where `testin*` does not match `testout*` will fail the test.

This behavior has been verified for `/gpu/hip/ref` and `/cpu/self`. 

Side questions:
- Is it `CeedOperatorLinearAssemble` and `CeedOperatorLinearAssembleDiagonal`, or just one of them?

### PR DESCRIPTION
**Pull request by jeremylt**
fixes #987

Before:
```
jeth8984@noether:/projects/jeremy/ratel$ make prove -j search=t103 PROVE_OPTS=-v
------------------------------------
--------------- RATEL --------------
------------------------------------

CEED_DIR      = /projects/jeremy/libCEED
PETSC_DIR     = /projects/ratel/petsc
PETSC_ARCH    = ratel-testing-serial

------------------------------------

Testing with libCEED backends: /cpu/self
Testing on 1 processes
prove -v --exec 'tests/tap.sh' t103-static-elasticity
t103-static-elasticity .. 
1..6
# Test Name: neo-hookean
# NPROC_TEST: 1
# TESTARGS: -ceed {ceed_resource} -yml tests/elasticity-neo-hookean-initial.yml
ok 1 t103-static-elasticity /cpu/self
not ok 2 t103-static-elasticity /cpu/self stdout
# + Error in Jacobian: Y_aij - Y_shell = 5.60089e+01
ok 3 t103-static-elasticity /cpu/self stderr
# Test Name: mooney-rivlin
# NPROC_TEST: 1
# TESTARGS: -ceed {ceed_resource} -yml tests/elasticity-mooney-rivlin-initial.yml
ok 4 t103-static-elasticity /cpu/self
not ok 5 t103-static-elasticity /cpu/self stdout
# + Error in Jacobian: Y_aij - Y_shell = 5.69579e+01
ok 6 t103-static-elasticity /cpu/self stderr
Failed 2/6 subtests 

Test Summary Report
-------------------
t103-static-elasticity (Wstat: 0 Tests: 6 Failed: 2)
  Failed tests:  2, 5
Files=1, Tests=6,  1 wallclock secs ( 0.01 usr  0.00 sys +  0.50 cusr  0.15 csys =  0.66 CPU)
Result: FAIL
make: *** [Makefile:357: prove] Error 1
```

After:
```
jeth8984@noether:/projects/jeremy/ratel$ make prove -j search=t103 PROVE_OPTS=-v
------------------------------------
--------------- RATEL --------------
------------------------------------

CEED_DIR      = /projects/jeremy/libCEED
PETSC_DIR     = /projects/ratel/petsc
PETSC_ARCH    = ratel-testing-serial

------------------------------------

Testing with libCEED backends: /cpu/self
Testing on 1 processes
prove -v --exec 'tests/tap.sh' t103-static-elasticity
t103-static-elasticity .. 
1..6
# Test Name: neo-hookean
# NPROC_TEST: 1
# TESTARGS: -ceed {ceed_resource} -yml tests/elasticity-neo-hookean-initial.yml
ok 1 t103-static-elasticity /cpu/self
ok 2 t103-static-elasticity /cpu/self stdout
ok 3 t103-static-elasticity /cpu/self stderr
# Test Name: mooney-rivlin
# NPROC_TEST: 1
# TESTARGS: -ceed {ceed_resource} -yml tests/elasticity-mooney-rivlin-initial.yml
ok 4 t103-static-elasticity /cpu/self
ok 5 t103-static-elasticity /cpu/self stdout
ok 6 t103-static-elasticity /cpu/self stderr
ok
All tests successful.
Files=1, Tests=6,  1 wallclock secs ( 0.02 usr  0.00 sys +  0.53 cusr  0.13 csys =  0.68 CPU)
Result: PASS
```

### CODE REVIEW

**Comment by jeremylt** [comment]
This streamlines the implementation on the CPU side and fixes some indexing  irregularities, but unfortunately this does not actually fix the issue.

**Comment by jrwrigh** [comment]
Yep, works on my side!

**Comment by jeremylt** [comment]
@nbeams, I haven't found the issue yet on the GPU side, but on the CPU side it was a mixup of using `num_eval_mode_in` vs `num_eval_mode_out`

File: interface/ceed-preconditioning.c [hunk 1]
```diff
@@ -800,99 +664,46 @@ static int CeedSingleOperatorAssemble(CeedOperator op, CeedInt offset,
   ierr = CeedElemRestrictionDestroy(&rstr_q); CeedChk(ierr);
 
   // we store B_mat_in, B_mat_out, BTD, elem_mat in row-major order
-  CeedScalar B_mat_in[(num_qpts * num_eval_mode_in) * elem_size];
-  CeedScalar B_mat_out[(num_qpts * num_eval_mode_out) * elem_size];
```
Comment (jeremylt) [inline interface/ceed-preconditioning.c:804]: I'd imagine that caching these matrices rather than rebuilding them for every single element, each time we assemble the operator, will speed up CPU assembly.

**Comment by nbeams** [comment]
> it was a mixup of using num_eval_mode_in vs num_eval_mode_out

Where was this mixup/where was it swapped?

File: interface/ceed-preconditioning.c [hunk 2]
```diff
@@ -800,99 +664,46 @@ static int CeedSingleOperatorAssemble(CeedOperator op, CeedInt offset,
...
+            for (CeedInt e_in = 0; e_in < num_eval_mode_in; e_in++) {
+              for (CeedInt e_out = 0; e_out < num_eval_mode_out; e_out++) {
+                const CeedInt btd_index = n*(num_qpts*num_eval_mode_in) +
+                                          (num_eval_mode_in*q + e_in);
+                const CeedInt b_out_index = (num_eval_mode_out*q + e_out)*elem_size + n;
+                const CeedInt eval_mode_index = ((e_in*num_comp+comp_in)*num_eval_mode_out
+                                                 +e_out)*num_comp + comp_out;
+                const CeedInt qf_index = q*layout_qf[0] + eval_mode_index*layout_qf[1] +
+                                         e*layout_qf[2];
+                if (fabs(assembled_qf_array[qf_index]) > qf_value_bound) {
```
Comment (nbeams) [inline interface/ceed-preconditioning.c:692]: I don't think we actually want this check here, do we?  We didn't have it previously in operator assembly (just diagonal assembly and FDMElementInverse).

**Comment by nbeams** [comment]
When you say you haven't found the GPU issue yet, do you mean in Ratel?  It looks like t568 passes for /gpu/hip/ref.

File: interface/ceed-preconditioning.c (hunk 2 above)
Comment (jeremylt) [reply interface/ceed-preconditioning.c:692]: I don't see why not. If it is useful for diagonal assembly, its useful for full assembly as well. The idea was to reduce rounding noise from nearly zero entries in D.

**Comment by jeremylt** [comment]
> When you say you haven't found the GPU issue yet, do you mean in Ratel? It looks like t568 passes for /gpu/hip/ref.

Yeah, Ratel with that small patch listed in the issue. Strangely, t568 doesn't replicate the issue even though it seems to be the same setup to me.

**Comment by jeremylt** [comment]
Huh, I'm not able to reproduce on GPU
```
jeth8984@noether:/projects/jeremy/ratel$ make prove -j search=t103 PROVE_OPTS=-v CEED_BACKENDS=/gpu/hip
------------------------------------
--------------- RATEL --------------
------------------------------------

CEED_DIR      = /projects/jeremy/libCEED
PETSC_DIR     = /projects/ratel/petsc
PETSC_ARCH    = ratel-testing-serial

------------------------------------

Testing with libCEED backends: /gpu/hip
Testing on 1 processes
prove -v --exec 'tests/tap.sh' t103-static-elasticity
t103-static-elasticity .. 
1..6
# Test Name: neo-hookean
# NPROC_TEST: 1
# TESTARGS: -ceed {ceed_resource} -yml tests/elasticity-neo-hookean-initial.yml
ok 1 t103-static-elasticity /gpu/hip
ok 2 t103-static-elasticity /gpu/hip stdout
ok 3 t103-static-elasticity /gpu/hip stderr
# Test Name: mooney-rivlin
# NPROC_TEST: 1
# TESTARGS: -ceed {ceed_resource} -yml tests/elasticity-mooney-rivlin-initial.yml
ok 4 t103-static-elasticity /gpu/hip
ok 5 t103-static-elasticity /gpu/hip stdout
ok 6 t103-static-elasticity /gpu/hip stderr
ok
All tests successful.
Files=1, Tests=6, 32 wallclock secs ( 0.01 usr  0.00 sys + 31.14 cusr  0.56 csys = 31.71 CPU)
Result: PASS
```

File: interface/ceed-preconditioning.c (hunk 2 above)
Comment (nbeams) [reply interface/ceed-preconditioning.c:692]: Well, for one thing, the other two routines (assemble diagonal and FDMElementInverse) are only meant for preconditioning purposes, no?  Whereas matrix assembly is billed as assembling the exact same operator as the "standard" matrix-free application.  We don't remove any noise from the QFunction application in that case.

Comment (jeremylt) [reply interface/ceed-preconditioning.c:692]: Diagonal assembly is billed as the exact, true diagonal of the assembled operator. Likely, it won't make a difference, so we can probably just strip in from both diagonal and full assembly.

**Comment by jrwrigh** [comment]
I'm AFK right now, but I believe I had used `/gpu/hip/ref`. I also tried it on this branch and the test still failed.

**Comment by nbeams** [comment]
And strangely, I'm seeing failures for t103 (using the command above) for `/gpu/hip` even on the Ratel main branch, with*out* the patch applied.  And also a failure in the Mooney-Rivlin t103 for `/cpu/self/ref`.  So...really not sure what's going on with my build...

**Comment by jeremylt** [comment]
Odd, Ratel t103 works for me on my local machine, in CI on Noether, and manually on Noether. I checked manually with CPU and GPU, on Ratel main + libCEED main and with that Ratel patch + this libCEED branch.

**Comment by jeremylt** [comment]
Ok, Ratel CI has PETSc main as of 12 April and HIP backends work fine then. But as of more recent builds something has broken (again?) with GPU assembly on the PETSc side of the house. I can bisect later this morning.

Using @nbeams most recent build of PETSc
```
Testing with libCEED backends: /gpu/hip
Testing on 1 processes
prove -v --exec 'tests/tap.sh' t103-static-elasticity
t103-static-elasticity .. 
1..6
# Test Name: neo-hookean
# NPROC_TEST: 1
# TESTARGS: -ceed {ceed_resource} -yml tests/elasticity-neo-hookean-initial.yml
ok 1 t103-static-elasticity /gpu/hip
not ok 2 t103-static-elasticity /gpu/hip stdout
# + Error in Jacobian: Y_aij - Y_shell = 1.38455e+01
ok 3 t103-static-elasticity /gpu/hip stderr
# Test Name: mooney-rivlin
# NPROC_TEST: 1
# TESTARGS: -ceed {ceed_resource} -yml tests/elasticity-mooney-rivlin-initial.yml
ok 4 t103-static-elasticity /gpu/hip
not ok 5 t103-static-elasticity /gpu/hip stdout
# + Error in Jacobian: Y_aij - Y_shell = 1.66808e+01
ok 6 t103-static-elasticity /gpu/hip stderr
Failed 2/6 subtests 

Test Summary Report
-------------------
t103-static-elasticity (Wstat: 0 Tests: 6 Failed: 2)
  Failed tests:  2, 5
Files=1, Tests=6, 31 wallclock secs ( 0.01 usr  0.00 sys + 30.23 cusr  0.91 csys = 31.15 CPU)
Result: FAIL
make: *** [Makefile:357: prove] Error 1
```

**Comment by jeremylt** [comment]
Ok, the HIP issue is unrelated and being investigated separately.

**Comment by jedbrown** [comment]
Can anyone else confirm behavior on CUDA? Without valgrind, it still seg-faults here. I don't know why valgrind isn't tracking origins like it usually does.
```
$ valgrind --track-origins=yes build/t103-static-elasticity -ceed /gpu/cuda -yml tests/elasticity-neo-hookean-initial.yml
[...]
==171597== Invalid read of size 8
==171597==    at 0x53B6C37: MatSetValuesCOO_SeqAIJ (aij.c:4765)
==171597==    by 0x5458FAE: MatSetValuesCOO (gcreate.c:692)
==171597==    by 0x487B140: RatelMatSetValuesCOO (ratel-petsc-ops.c:143)
==171597==    by 0x487C254: RatelSNESFormJacobian (ratel-petsc-ops.c:436)
==171597==    by 0x589C713: SNESComputeJacobian (snes.c:2830)
==171597==    by 0x109F5F: main (t103-static-elasticity.c:63)
==171597==  Address 0x160800b60 is in a --- anonymous segment
```
Cc: @jczhang07

**Comment by jeremylt** [comment]
All of the CUDA + libCEED pass locally for me, so it has to be something over in CUDA + libCEED + PETSc. I'm chasing the HIP + Ratel thing, but I can circle back to this.

**Comment by jedbrown** [comment]
In `t103`, why do you force the matrix type to "aij" even when values will be computed on the GPU?
```diff
diff --git i/tests/t103-static-elasticity.c w/tests/t103-static-elasticity.c
index 78ebef9..74de0e7 100644
--- i/tests/t103-static-elasticity.c
+++ w/tests/t103-static-elasticity.c
@@ -36,7 +36,7 @@ int main(int argc, char **argv) {
   PetscCall(RatelDMCreate(ratel_shell, RATEL_METHOD_STATIC_ELASTICITY, &dm_shell));
 
   // Initalize Ratel context and DM for MATAIJ
-  PetscCall(PetscOptionsInsertString(NULL, "-fine_dm_mat_type aij"));
+  //PetscCall(PetscOptionsInsertString(NULL, "-fine_dm_mat_type aij"));
   PetscCall(RatelInit(comm, yml_path, &ratel_aij));
   PetscCall(RatelDMCreate(ratel_aij, RATEL_METHOD_STATIC_ELASTICITY, &dm_aij));
 
```
This passes now
```console
$ build/t103-static-elasticity -ceed /gpu/cuda -yml tests/elasticity-neo-hookean-initial.yml -fine_dm_mat_type aijcusparse
```

**Comment by jeremylt** [comment]
I thought it would be fun to create a bug that would take forever to find and would totally confuse me:
```
$ make prove -j PROVE_OPTS=-v CEED_BACKENDS=/gpu/hip search="t102 t103"
------------------------------------
--------------- RATEL --------------
------------------------------------

CEED_DIR      = /projects/ratel/libCEED
PETSC_DIR     = /projects/ratel/petsc
PETSC_ARCH    = ratel-testing-parallel/

------------------------------------

      LINK.c build/t102-static-elasticity
      LINK.c build/t103-static-elasticity
Testing with libCEED backends: /gpu/hip
Testing on 1 processes
prove -v --exec 'tests/tap.sh' t102-static-elasticity t103-static-elasticity
t102-static-elasticity .. 
1..9
# Test Name: linear-box
# NPROC_TEST: 1
# TESTARGS: -ceed {ceed_resource} -yml tests/elasticity-linear.yml
ok 1 t102-static-elasticity /gpu/hip
ok 2 t102-static-elasticity /gpu/hip stdout
ok 3 t102-static-elasticity /gpu/hip stderr
# Test Name: linear-simplex
# NPROC_TEST: 1
# TESTARGS: -ceed {ceed_resource} -yml tests/elasticity-linear-simplex.yml
ok 4 # SKIP - not implemented t102-static-elasticity /gpu/hip
ok 5 # SKIP - not implemented t102-static-elasticity /gpu/hip stdout
ok 6 # SKIP - not implemented t102-static-elasticity /gpu/hip stderr
# Test Name: linear-quad-coords
# NPROC_TEST: 1
# TESTARGS: -ceed {ceed_resource} -yml tests/elasticity-linear-quad-coords.yml
ok 7 t102-static-elasticity /gpu/hip
ok 8 t102-static-elasticity /gpu/hip stdout
ok 9 t102-static-elasticity /gpu/hip stderr
ok
t103-static-elasticity .. 
1..6
# Test Name: neo-hookean
# NPROC_TEST: 1
# TESTARGS: -ceed {ceed_resource} -yml tests/elasticity-neo-hookean-initial.yml
ok 1 t103-static-elasticity /gpu/hip
ok 2 t103-static-elasticity /gpu/hip stdout
ok 3 t103-static-elasticity /gpu/hip stderr
# Test Name: mooney-rivlin
# NPROC_TEST: 1
# TESTARGS: -ceed {ceed_resource} -yml tests/elasticity-mooney-rivlin-initial.yml
ok 4 t103-static-elasticity /gpu/hip
ok 5 t103-static-elasticity /gpu/hip stdout
ok 6 t103-static-elasticity /gpu/hip stderr
ok
All tests successful.
Files=2, Tests=15, 62 wallclock secs ( 0.02 usr  0.00 sys + 59.99 cusr  2.09 csys = 62.10 CPU)
Result: PASS
```

**Comment by jczhang07** [comment]
With cuda, I could not reproduce the problem (petsc + --with-mpi=1 fails but --with-mpi=0 works). Even with --with-mpi=0, I saw the segfault.

But on Neother,  if with MPI,  I could see the difference: `aijkokkos` worked but `aij` did not
```
$ build/t103-static-elasticity -ceed /gpu/hip -yml tests/elasticity-mooney-rivlin-initial.yml -fine_dm_mat_type aijkokkos
[junchaozhang@noether ~/ratel]$ $ arch-kokkos-dbg  
$ build/t103-static-elasticity -ceed /gpu/hip -yml tests/elasticity-mooney-rivlin-initial.yml -fine_dm_mat_type aij
Error in Jacobian: Y_aij - Y_shell = 1.98200e+01
```
but with petsc + --with-mpi=0, passing `-fine_dm_mat_type aijkokkos` or `aij` both worked!  

I found no matter passing  `aijkokkos` or `aij`, the `v[]` pointer I got either in `MatSetValuesCOO_SeqAIJKokkos` or `MatSetValuesCOO_SeqAIJ` were always on device (queried with `PetscGetMemType(v,&mtype)`) . 

And in gdb, I could even dereference v and it seems it printed correct values. 
```
$ gdb --args build/t103-static-elasticity -ceed /gpu/hip -yml tests/elasticity-mooney-rivlin-initial.yml -fine_dm_mat_type aij
...
Thread 1 "t103-static-ela" hit Breakpoint 1, MatSetValuesCOO_SeqAIJ (A=0x55555b46fc80, v=0x7ffe7fc74000, imode=INSERT_VALUES)

(gdb) p *v@100
$1 = {0.067723598314379893, -0.034535607923534488, -0.00056877624915453392, -0.0099996044916418978, -0.0021887520665953009, 0.013881130847605607, -0.0078973923742420588, 
  0.0047515444854063895, -0.0039128122568308108, -0.0099996044916419134, -0.002188752066595303, 0.013881130847605613, -0.047314508741508388, -0.0047444077027777275, 
…
}
```

**Review by jedbrown — APPROVED** [review]
